version: "1"
rules:
  - base: main
    upstream: google:main
    mergeMethod: merge
    mergeUnstable: false
    assignees:
      - goknsh
    reviewers:
      - goknsh
    conflictReviewers:
      - goknsh
